version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-taskman
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: taskmanager_db
      MYSQL_USER: taskuser
      MYSQL_PASSWORD: taskpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - taskman-net

volumes:
  mysql_data:

networks:
  taskman-net:
    driver: bridge
